/* __imports_rewritten__ */
import {Smartphone, Shirt, ChefHat, Sofa, CarFront, Moon, SunMedium, Search, ShoppingBag, Heart, UserCircle2, Menu, X, Star, ArrowRight, Trash2, Plus, Minus, ShieldCheck, CreditCard, Truck, Sparkles, BadgeCheck, LayoutDashboard, Save, Pencil, Mail, Phone, MessageCircle, Send, KeyRound, PackageCheck, Globe, Eye, EyeOff, Languages} from 'https://esm.sh/lucide-react?deps=react@19.2.0';

export const iconMap = {
  Smartphone,
  Shirt,
  ChefHat,
  Sofa,
  CarFront,
  Moon,
  SunMedium,
  Search,
  ShoppingBag,
  Heart,
  UserCircle2,
  Menu,
  X,
  Star,
  ArrowRight,
  Trash2,
  Plus,
  Minus,
  ShieldCheck,
  CreditCard,
  Truck,
  Sparkles,
  BadgeCheck,
  LayoutDashboard,
  Save,
  Pencil,
  Mail,
  Phone,
  MessageCircle,
  Send,
  KeyRound,
  PackageCheck,
  Globe,
  Eye,
  EyeOff,
  Languages
};
