export const translations = {
  en: {
    home: 'Home', shop: 'Products', electronics: 'Electronics', clothes: 'Clothes', contact: 'Contact', admin: 'Admin', adminDashboard: 'Admin dashboard', cart: 'Cart', checkout: 'Checkout', loginSignup: 'Login / Signup', adminAccount: 'Admin account', searchPlaceholder: 'Search phones, shoes, chargers, furniture...', searchMobile: 'Search products', toggleLanguage: 'Switch language', signedIn: 'You are signed in', adminSession: 'Admin session', customerSession: 'Customer session', loggedInAs: 'Logged in as', adminAccessInfo: 'Use the secure dashboard to manage products, orders, and password changes.', customerInfo: 'You are signed in to your Yuyu shopping account.', goHome: 'Go home', logout: 'Logout', yuyuAccount: 'Yuyu account', authTitle: 'Welcome back to Yuyu.', authIntro: 'Sign in to manage your wishlist, review your cart, and enjoy a smoother shopping flow across all Yuyu categories.', login: 'Login', signup: 'Signup', fullName: 'Full name', emailAddress: 'Email address', password: 'Password', show: 'Show', hide: 'Hide', pleaseWait: 'Please wait...', createAccount: 'Create account', googleSignIn: 'Continue with Google', magicLink: 'Send magic link', checkEmail: 'Check your email for the sign-in link.', emailRequired: 'Email is required.', invalidEmail: 'Enter a valid email address.', passwordRequired: 'Password is required.', shortPassword: 'Password must be at least 6 characters.', nameRequired: 'Full name is required.', wrongPassword: 'Incorrect email or password.', authHelp: 'Admin login is handled securely by the backend. Customer email sign-in uses the built-in authentication when available.'
  },
  am: {
    home: 'መነሻ', shop: 'ምርቶች', electronics: 'ኤሌክትሮኒክስ', clothes: 'ልብሶች', contact: 'አግኙን', admin: 'አስተዳዳሪ', adminDashboard: 'የአስተዳዳሪ ዳሽቦርድ', cart: 'ጋሪ', checkout: 'መግዛት', loginSignup: 'ግባ / ተመዝገብ', adminAccount: 'የአስተዳዳሪ መለያ', searchPlaceholder: 'ስልኮች፣ ጫማዎች፣ ቻርጀሮች፣ ፈርኒቸር ፈልግ...', searchMobile: 'ምርቶችን ፈልግ', toggleLanguage: 'ቋንቋ ቀይር', signedIn: 'ገብተዋል', adminSession: 'የአስተዳዳሪ ክፍለ ጊዜ', customerSession: 'የደንበኛ ክፍለ ጊዜ', loggedInAs: 'የገቡት በ', adminAccessInfo: 'ምርቶችን፣ ትዕዛዞችን እና የይለፍ ቃል ለውጦችን ለመቆጣጠር ደህንነቱ የተጠበቀውን ዳሽቦርድ ይጠቀሙ።', customerInfo: 'ወደ Yuyu የግብይት መለያዎ ገብተዋል።', goHome: 'ወደ መነሻ', logout: 'ውጣ', yuyuAccount: 'የYuyu መለያ', authTitle: 'እንኳን ወደ Yuyu ተመለሱ።', authIntro: 'የሚወዷቸውን ለመቆጣጠር፣ ጋሪዎን ለመመልከት እና ቀላል የግብይት ተሞክሮ ለማግኘት ይግቡ።', login: 'ግባ', signup: 'ተመዝገብ', fullName: 'ሙሉ ስም', emailAddress: 'ኢሜይል', password: 'የይለፍ ቃል', show: 'አሳይ', hide: 'ደብቅ', pleaseWait: 'እባክዎ ይጠብቁ...', createAccount: 'መለያ ፍጠር', googleSignIn: 'በGoogle ቀጥል', magicLink: 'የመግቢያ ሊንክ ላክ', checkEmail: 'የመግቢያ ሊንኩን በኢሜይልዎ ይመልከቱ።', emailRequired: 'ኢሜይል ያስፈልጋል።', invalidEmail: 'ትክክለኛ ኢሜይል ያስገቡ።', passwordRequired: 'የይለፍ ቃል ያስፈልጋል።', shortPassword: 'የይለፍ ቃል ቢያንስ 6 ፊደላት መሆን አለበት።', nameRequired: 'ሙሉ ስም ያስፈልጋል።', wrongPassword: 'ኢሜይል ወይም የይለፍ ቃል ትክክል አይደለም።', authHelp: 'የአስተዳዳሪ መግቢያ በኋላ ሰርቨር በደህንነት ይሰራል። የደንበኛ ኢሜይል መግቢያ ካለ የተገነባውን ማረጋገጫ ይጠቀማል።'
  },
  ar: {
    home: 'الرئيسية', shop: 'المنتجات', electronics: 'الإلكترونيات', clothes: 'الملابس', contact: 'اتصل بنا', admin: 'المدير', adminDashboard: 'لوحة تحكم المدير', cart: 'السلة', checkout: 'الدفع', loginSignup: 'تسجيل الدخول / إنشاء حساب', adminAccount: 'حساب المدير', searchPlaceholder: 'ابحث عن هواتف، أحذية، شواحن، أثاث...', searchMobile: 'ابحث عن المنتجات', toggleLanguage: 'تغيير اللغة', signedIn: 'تم تسجيل الدخول', adminSession: 'جلسة المدير', customerSession: 'جلسة العميل', loggedInAs: 'تم الدخول باسم', adminAccessInfo: 'استخدم لوحة التحكم الآمنة لإدارة المنتجات والطلبات وتغيير كلمة المرور.', customerInfo: 'أنت مسجل الدخول إلى حساب التسوق في Yuyu.', goHome: 'العودة للرئيسية', logout: 'تسجيل الخروج', yuyuAccount: 'حساب Yuyu', authTitle: 'مرحباً بعودتك إلى Yuyu.', authIntro: 'سجّل الدخول لإدارة المفضلة ومراجعة السلة والاستمتاع بتجربة تسوق أسهل في جميع أقسام Yuyu.', login: 'تسجيل الدخول', signup: 'إنشاء حساب', fullName: 'الاسم الكامل', emailAddress: 'البريد الإلكتروني', password: 'كلمة المرور', show: 'إظهار', hide: 'إخفاء', pleaseWait: 'يرجى الانتظار...', createAccount: 'إنشاء حساب', googleSignIn: 'المتابعة باستخدام Google', magicLink: 'إرسال رابط الدخول', checkEmail: 'تحقق من بريدك الإلكتروني للحصول على رابط تسجيل الدخول.', emailRequired: 'البريد الإلكتروني مطلوب.', invalidEmail: 'أدخل بريداً إلكترونياً صحيحاً.', passwordRequired: 'كلمة المرور مطلوبة.', shortPassword: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.', nameRequired: 'الاسم الكامل مطلوب.', wrongPassword: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', authHelp: 'يتم تسجيل دخول المدير بأمان عبر الخادم. تسجيل دخول العملاء بالبريد يستخدم خدمة المصادقة المدمجة عند توفرها.'
  }
};

export function t(language, key) {
  return translations[language]?.[key] || translations.en[key] || key;
}
